### PR TITLE
feat: add message payload

### LINKED ISSUE #98: Allow string to interaction#reply
Allow users to pass just a string to interaction#reply instead of the full object and have that be set to the content internally

### PR DESCRIPTION
**Pull request by thewilloftheshadow**
Closes #98

### CODE REVIEW

**Comment by apteryxxyz** [comment]
When I was talking about `MessagePayload` I was referring to more of an internal class, that allowed you to do something like this:
```ts
const payload = new MessagePayload(options)
const body = payload.getBody()
const files = payload.getFiles()
// send body and files to some api endpoint
```
And on a side note, a lot of send methods are missing the ability to send files. The purpose of this idea being to make that part more reusable. Though this looks fine so if you had another idea thats fine

**Comment by thewilloftheshadow** [comment]
Wait so are you thinking something like
```
send(new MessagePayload({content: ""})
```
or more along the lines of this:
```ts
const send = (data) => {
  const payload = new MessagePayload(data)
  processRequest(payload)
}

send({content: "hi"})
```

**Comment by apteryxxyz** [comment]
The latter, check Discord

**Comment by thewilloftheshadow** [comment]
Gonna merge this as an intermediary step

**Pull request merged**
